<?php require_once 'config.php'; ?>
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo htmlspecialchars($config['app_title'] ?? 'Photo Gallery'); ?></title>
    <link rel="icon" type="image/png" href="theme/favicon.png"> <!-- Favicon -->
    <!-- Corrected PhotoSwipe 5 CSS CDN -->
    <link rel="stylesheet" href="https://unpkg.com/photoswipe@5/dist/photoswipe.css">
    <!-- Your custom styles -->
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header class="app-header">
        <div class="container header-container">
            <a href="#" class="logo-link" aria-label="Trang chủ Guustudio">
                <!-- Updated Logo Path (Relative) -->
                <img src="theme/logo.png" alt="Guustudio Logo" id="site-logo"> 
            </a>
            <div class="header-actions">
                 <button id="backButton" class="button back-button" style="display: none;">← Quay lại</button>
                 <!-- Add other potential header links/buttons here -->
            </div>
        </div>
    </header>

    <main class="container user-view">
        <!-- Thêm loading indicator ở đây -->
        <div id="loading-indicator" style="display: none; text-align: center; padding: 20px;">
            <p>Đang tải...</p> 
            <!-- Bạn có thể thêm spinner CSS hoặc ảnh GIF ở đây nếu muốn -->
        </div>

        <div id="directory-view">
            <div class="search-container google-style">
                <input type="search" id="searchInput" placeholder="Tìm album ảnh (tên lớp, trường,...)" aria-label="Tìm kiếm album">
                <!-- Thêm nút clear search -->
                <button id="clearSearch" class="clear-search-button" style="display: none;" aria-label="Xóa tìm kiếm">&times;</button>
            </div>
            <p id="search-prompt" class="search-prompt">
                Nhập từ khóa để tìm album ảnh của bạn.
            </p>

            <ul id="directory-list" class="directory-list-styling">
                <!-- Search results -->
            </ul>
        </div>

        <div id="image-view" style="display: none;">
            <div class="image-view-header">
                <h2 id="current-directory-name"></h2>
                 <div class="image-view-actions">
                    <button id="shareButton" class="button share-button">Sao chép Link</button>
                    <a id="download-all-link" href="#" class="button download-all">Tải tất cả (ZIP)</a>
                 </div>
            </div>
            <div id="image-grid"></div>
            <div id="load-more-container" style="text-align: center; margin-top: 20px; display: none;">
                <button id="loadMoreBtn" class="button">Tải thêm ảnh</button>
            </div>
        </div>
    </main>

    <!-- REMOVED old Preview Overlay -->
    <!-- PhotoSwipe requires no static HTML for its overlay -->

    <!-- Password Prompt -->
    <div id="passwordPromptOverlay" class="modal-overlay" style="display: none;">
        <!-- Add modal-box and keep specific class -->
        <div class="modal-box password-prompt-box">
            <!-- Content generated by JS -->
        </div>
    </div>

    <footer class="app-footer">
        <div class="container footer-container">
            <p>&copy; 2025 <a href="https://guustudio.vn" target="_blank" rel="noopener noreferrer">Guustudio.vn</a> - Buôn Ma Thuột - Đắk Lắk</p>
             <p class="footer-contact">Liên hệ: 0914 896 870 | Email: guustudio.bmt@gmail.com</p> 
        </div>
    </footer>

    <!-- App JS (Load as module because it uses import) -->
    <!-- PhotoSwipe JS module will be imported *within* app.js -->
    <script type="module" src="js/app.js"></script> 

    <!-- ADDED: Zip Progress Overlay -->
    <div id="zip-progress-overlay" class="modal-overlay" style="display: none !important;">
        <!-- Add modal-box and keep specific class -->
        <div class="modal-box zip-progress-box">
            <div class="spinner"></div>
            <p id="zip-progress-message" style="margin-top: 15px; margin-bottom: 20px;">Đang chuẩn bị file ZIP...</p>
            <button id="cancel-zip-button" class="button" style="background:#6c757d;">Hủy bỏ</button>
        </div>
    </div>

</body>
</html>